### ISSUE TITLE
Summarizer not working

### ISSUE THREAD

**Issue by vascofl** [Azure-Samples/function-python-ai-textsummarize#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Clone the repo and do the steps indicated in the READ.ME

### Any log messages given by the failure
>
I deployed the app to azure and when I use F5 to run it i get this pop-up error:
![image](https://github.com/Azure-Samples/function-python-ai-textsummarize/assets/72892420/3b7bbbe5-e292-4592-9c95-dc7e97fc95d3)
And in the output I get this error:
![image](https://github.com/Azure-Samples/function-python-ai-textsummarize/assets/72892420/e817cd69-360a-404b-810a-7b3ab9b8b45c)
I also get this warning in the launch.json:
![image](https://github.com/Azure-Samples/function-python-ai-textsummarize/assets/72892420/b8187285-5b53-49ff-8593-5cd4754227d6)
I manually created the test-samples-trigger container and loaded it with a text file to summarize but it didn't do anything, I also tried to create the test-samples-output manually but the app did not generate any summary. The other two azure-webjobs containers were created automatically by the app I think:
![image](https://github.com/Azure-Samples/function-python-ai-textsummarize/assets/72892420/219805bd-2090-4a01-8467-7dd537fa1c06)
Here is the full output that I got after running the app:
[Output.txt](https://github.com/Azure-Samples/function-python-ai-textsummarize/files/15042158/Output.txt)

### Expected/desired behavior
>
App to summarize the .txt files I feed it

### OS and Version?
> Windows 10

### Versions
>
Python 3.10
### Mention any other details that might be useful
I already tried to reinstall azure-core azure-ai-textanalytics but it didn't help
Thank you in advance for your help :)
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by paulyuk** [comment]
Hi,  thank you for this report and sorry for the non working experience.  I'm taking a look..
